version: '3.1'
services:

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: BeerData
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306